# AppVeyor CI build file

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# version format
version: 1.0.{build}

shallow_clone: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  project: CertiPay.Payroll.Common.sln

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - CertiPay.Payroll.Common.Tests.dll

#---------------------------------#
#       artifacts configuration   #
#---------------------------------#

nuget:
  account_feed: true
  project_feed: true

on_success:
  - cmd: NuGet pack CertiPay.Payroll.Common\CertiPay.Payroll.Common.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - ps: Push-AppveyorArtifact "CertiPay.Payroll.Common.$($env:APPVEYOR_BUILD_VERSION).nupkg"

deploy:
- provider: NuGet
  api_key:
    secure: tj8axlUnLaJXMzsVHzNj6dT8VROvH1ChDSv9bKkQG4oNRB/6pI4oefW5WAhuIDIE