# AppVeyor CI build file

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# version format
version: 1.2.{build}

shallow_clone: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
- cmd: nuget restore

after_build:
- dotnet pack "CertiPay.Payroll.Common" --configuration %CONFIGURATION% --version-suffix %APPVEYOR_BUILD_NUMBER%

build:
  publish_nuget: true

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - CertiPay.Payroll.Common.Tests.dll

#---------------------------------#
#       artifacts configuration   #
#---------------------------------#

deploy:
- provider: NuGet
  on: 
    branch: master
  api_key:
    secure: tj8axlUnLaJXMzsVHzNj6dT8VROvH1ChDSv9bKkQG4oNRB/6pI4oefW5WAhuIDIE